export const dynamic = "force-dynamic";

import { requireAuth } from "@/lib/auth";
import { getDemandSnapshot, type FunnelWindow } from "@/lib/analytics/funnel";

/**
 * The demand gauge.
 *
 * Every other admin surface here answers "what is broken in the data". This one
 * answers "is anyone trying to buy" — the question nothing in this codebase
 * could previously answer without a manual query.
 */

const ROWS: Array<{ key: keyof FunnelWindow; label: string; hint: string }> = [
  { key: "leads", label: "Leads", hint: "Contact form, sample requests, lead capture" },
  { key: "reportRequests", label: "Report requests", hint: "Email-gated report downloads" },
  { key: "registrations", label: "Registrations", hint: "Accounts created" },
  { key: "reportsGenerated", label: "Reports generated", hint: "On-demand generations, all types" },
  { key: "paying", label: "Paying", hint: "Current subscriptions — a total, not a window" },
];

function Stat({ value, muted }: { value: number; muted?: boolean }) {
  return (
    <span
      className={`font-mono text-2xl tabular-nums ${
        muted || value === 0
          ? "text-gray-400 dark:text-gray-600"
          : "text-gray-900 dark:text-gray-100"
      }`}
    >
      {value.toLocaleString()}
    </span>
  );
}

export default async function AdminDemandPage() {
  await requireAuth("view");
  const snapshot = await getDemandSnapshot();
  const week = snapshot.windows.find((w) => w.days === 7);
  const month = snapshot.windows.find((w) => w.days === 30);

  return (
    <main className="mx-auto w-full max-w-4xl px-6 py-12">
      <h1 className="text-2xl font-semibold tracking-tight text-gray-900 dark:text-gray-100">
        Demand
      </h1>
      <p className="mt-2 max-w-[62ch] text-sm leading-relaxed text-gray-600 dark:text-gray-400">
        Counted from our own tables, not from analytics, so an ad blocker cannot
        change these numbers. A row of zeros is a real answer — it means nobody
        reached that step, which is worth knowing today rather than in a month.
      </p>

      <div className="mt-9 overflow-x-auto">
        <table className="w-full border-collapse text-left">
          <thead>
            <tr className="border-b border-gray-300 dark:border-gray-700">
              <th className="pb-3 text-[11px] font-medium uppercase tracking-[0.14em] text-gray-500">
                Step
              </th>
              <th className="pb-3 text-right text-[11px] font-medium uppercase tracking-[0.14em] text-gray-500">
                Last 7 days
              </th>
              <th className="pb-3 text-right text-[11px] font-medium uppercase tracking-[0.14em] text-gray-500">
                Last 30 days
              </th>
            </tr>
          </thead>
          <tbody>
            {ROWS.map((row) => {
              const isTotal = row.key === "paying";
              return (
                <tr key={row.key} className="border-b border-gray-200 dark:border-gray-800">
                  <td className="py-4 pr-6 align-middle">
                    <div className="text-sm font-medium text-gray-900 dark:text-gray-100">
                      {row.label}
                    </div>
                    <div className="mt-0.5 text-xs text-gray-500 dark:text-gray-500">
                      {row.hint}
                    </div>
                  </td>
                  <td className="py-4 text-right align-middle">
                    <Stat value={Number(week?.[row.key] ?? 0)} />
                  </td>
                  <td className="py-4 text-right align-middle">
                    <Stat value={Number(month?.[row.key] ?? 0)} muted={isTotal} />
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      <section className="mt-12">
        <h2 className="text-sm font-semibold text-gray-900 dark:text-gray-100">
          Reports generated by type
        </h2>
        <p className="mt-1 text-xs text-gray-500 dark:text-gray-500">Last 30 days.</p>
        {snapshot.byReportType.length === 0 ? (
          <p className="mt-4 text-sm text-gray-500 dark:text-gray-500">
            No reports generated in the last 30 days.
          </p>
        ) : (
          <ul className="mt-4 flex flex-col gap-2">
            {snapshot.byReportType.map((r) => (
              <li
                key={r.reportType}
                className="flex items-baseline justify-between border-b border-gray-200 py-2 dark:border-gray-800"
              >
                <span className="text-sm text-gray-700 dark:text-gray-300">
                  {r.reportType.replace(/_/g, " ")}
                </span>
                <span className="font-mono text-sm tabular-nums text-gray-900 dark:text-gray-100">
                  {r.count.toLocaleString()}
                </span>
              </li>
            ))}
          </ul>
        )}
      </section>

      {snapshot.warnings.length > 0 && (
        <p className="mt-10 border-l-2 border-amber-500 pl-4 text-xs leading-relaxed text-gray-600 dark:text-gray-400">
          Could not read: {snapshot.warnings.join(", ")}. Those rows show zero
          because the query failed, not because the count is zero.
        </p>
      )}
    </main>
  );
}
