/**
 * State Fee Index Report — HTML Template (stub)
 *
 * Placeholder for the state-level fee index report.
 * Full implementation pending — this stub unblocks the build.
 */

import { wrapReport, coverPage, sectionHeader, footnote } from "../index";
import { SITE_NAME } from "@/lib/constants";

export interface StateFeeIndexReportInput {
  stateCode: string;
  stateName: string;
  generatedAt: string;
}

export function renderStateFeeIndexReport(
  input: StateFeeIndexReportInput,
): string {
  const { stateCode, stateName, generatedAt } = input;

  const body = [
    coverPage({
      title: `${stateName} Fee Index`,
      subtitle: `State-level fee analysis for ${stateCode}`,
      report_date: generatedAt,
    }),
    sectionHeader({ label: "Overview", title: `${stateName} Fee Landscape` }),
    `<p style="padding: 0 32px; color: #6b7280;">
      State fee index report template is under development.
      Full analysis for ${stateName} will be available in a future release.
    </p>`,
    footnote(`Report generated by ${SITE_NAME}. Data subject to verification.`),
  ].join("\n");

  return wrapReport(body, {
    title: `${stateName} Fee Index`,
    date: generatedAt,
  });
}
