interface InterpretationBlockProps {
  text: string;
}

/**
 * InterpretationBlock — Spec #2, D-08.
 *
 * Renders the 2-3 sentence plain-English summary generated by
 * generateInterpretation(). Always renders — even with minimal data.
 * Newsreader serif for the section label; warm background card.
 */
export function InterpretationBlock({ text }: InterpretationBlockProps) {
  return (
    <div className="rounded-lg border border-[#E8DFD1]/60 bg-[#FAF7F2]/70 px-5 py-4">
      <p
        className="text-[11px] font-bold uppercase tracking-[0.1em] text-[#A09788]"
        style={{ fontFamily: "Newsreader, Georgia, serif" }}
      >
        What this means
      </p>
      <p className="mt-2 text-[14px] leading-relaxed text-[#5A5347]">{text}</p>
    </div>
  );
}
