import { SITE_URL } from "@/lib/constants";

/**
 * Extract all markdown tables from text and convert to CSV.
 */
export function markdownTablesToCsv(markdown: string): string {
  const tableRegex = /(\|.+\|)\n(\|[-| :]+\|)\n((?:\|.+\|\n?)+)/g;
  const csvSections: string[] = [];

  let match;
  while ((match = tableRegex.exec(markdown)) !== null) {
    const headerLine = match[1];
    const bodyLines = match[3].trim().split("\n");

    const parseRow = (line: string) =>
      line
        .split("|")
        .filter(Boolean)
        .map((cell) => `"${cell.trim().replace(/"/g, '""')}"`)
        .join(",");

    const rows = [parseRow(headerLine), ...bodyLines.map(parseRow)];
    csvSections.push(rows.join("\n"));
  }

  return csvSections.join("\n\n");
}

/**
 * Check if markdown contains at least one table.
 */
export function hasMarkdownTable(markdown: string): boolean {
  return /\|.+\|\n\|[-| :]+\|\n\|.+\|/m.test(markdown);
}

/**
 * Download a string as a file in the browser.
 */
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Build a branded HTML report from markdown content.
 */
export function buildReportHtml(markdown: string, agentName: string): string {
  const date = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  // Convert markdown to HTML (reuse the chat's simple markdown logic)
  let html = markdown
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  // Headers
  html = html.replace(/^### (.+)$/gm, "<h3>$1</h3>");
  html = html.replace(/^## (.+)$/gm, "<h2>$1</h2>");
  html = html.replace(/^# (.+)$/gm, "<h1>$1</h1>");

  // Bold
  html = html.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");

  // Tables
  html = html.replace(
    /^(\|.+\|)\n(\|[-| :]+\|)\n((?:\|.+\|\n?)+)/gm,
    (_match: string, header: string, _sep: string, body: string) => {
      const headers = header
        .split("|")
        .filter((c: string) => c.trim())
        .map((c: string) => `<th>${c.trim()}</th>`)
        .join("");
      const rows = body
        .trim()
        .split("\n")
        .map((row: string) => {
          const cells = row
            .split("|")
            .filter((c: string) => c.trim())
            .map((c: string) => `<td>${c.trim()}</td>`)
            .join("");
          return `<tr>${cells}</tr>`;
        })
        .join("");
      return `<table><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table>`;
    }
  );

  // Lists
  html = html.replace(/^- (.+)$/gm, "<li>$1</li>");
  html = html.replace(/(<li>.*<\/li>\n?)+/g, "<ul>$&</ul>");

  // Paragraphs
  html = html.replace(/\n\n/g, "</p><p>");
  html = `<p>${html}</p>`;

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Fee Insight Research Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Georgia, 'Times New Roman', serif; max-width: 750px; margin: 0 auto; padding: 40px 24px; color: #1e293b; line-height: 1.7; }
  .header { border-bottom: 2px solid #1e293b; padding-bottom: 16px; margin-bottom: 32px; }
  .header h1 { font-size: 14px; letter-spacing: 0.1em; text-transform: uppercase; color: #64748b; font-weight: 600; }
  .header p { font-size: 12px; color: #94a3b8; margin-top: 4px; }
  h1 { font-size: 24px; margin: 24px 0 12px; }
  h2 { font-size: 18px; margin: 20px 0 10px; color: #0f172a; }
  h3 { font-size: 15px; margin: 16px 0 8px; color: #334155; }
  p { font-size: 14px; margin-bottom: 12px; }
  strong { color: #0f172a; }
  table { border-collapse: collapse; width: 100%; margin: 16px 0; font-family: -apple-system, sans-serif; font-size: 12px; }
  th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }
  th { background: #f8fafc; font-weight: 600; color: #475569; text-transform: uppercase; font-size: 10px; letter-spacing: 0.05em; }
  ul { margin: 8px 0 16px 20px; }
  li { font-size: 14px; margin-bottom: 4px; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; }
  @media print {
    body { padding: 20px; }
    .no-print { display: none; }
  }
</style>
</head>
<body>
<div class="header">
  <h1>Fee Insight</h1>
  <p>Research Analysis &mdash; ${date} &mdash; ${agentName}</p>
</div>
${html}
<div class="footer">
  <p>Generated by Fee Insight Research Platform</p>
  <p>For institutional access and custom analysis: ${SITE_URL.replace(/^https?:\/\//, "")}</p>
</div>
</body>
</html>`;
}
