#!/usr/bin/env bash
# Regenerate src/lib/agent-tools/types.generated.ts from fee_crawler.agent_tools.schemas.
# Run after editing Pydantic schemas; CI verifies with --check mode.
#
# Note: The schemas module is a package (fee_crawler/agent_tools/schemas/) after Plan
# 62A-05; pydantic2ts walks the package via the public API exposed through
# schemas/__init__.py, which re-exports every per-domain module added by Plans 07..10.

set -euo pipefail

OUTPUT="src/lib/agent-tools/types.generated.ts"
MODULE="fee_crawler.agent_tools.schemas"

command -v pydantic2ts >/dev/null 2>&1 || {
  echo "pydantic2ts not found. Install: pip install pydantic-to-typescript>=2.0" >&2
  exit 2
}

mkdir -p "$(dirname "$OUTPUT")"

# pydantic2ts generates a file; we prepend an AUTO-GENERATED header so reviewers see it.
TMPFILE="$(mktemp)"
pydantic2ts --module "$MODULE" --output "$TMPFILE"

{
  echo "// AUTO-GENERATED by scripts/gen-agent-tool-types.sh — DO NOT EDIT BY HAND."
  echo "// Source of truth: fee_crawler/agent_tools/schemas/ (package)"
  echo "// Regenerate: bash scripts/gen-agent-tool-types.sh"
  echo
  cat "$TMPFILE"
} > "$OUTPUT"

rm -f "$TMPFILE"

if [[ "${CHECK_MODE:-0}" == "1" ]]; then
  if ! git diff --exit-code -- "$OUTPUT" >/dev/null 2>&1; then
    echo "gen-agent-tool-types: $OUTPUT is stale. Regenerate locally and commit." >&2
    exit 1
  fi
fi

echo "gen-agent-tool-types: OK -> $OUTPUT"
