-- Published fee quality gate (Phase 1 of the sellable-intelligence plan, 2026-08-23).
--
-- Adds a quarantine flag to published_fee_records, canonical taxonomy + alias +
-- plausibility-band reference tables (seeded from the TypeScript sources of
-- truth via scripts/generate-fee-quality-seeds.mjs), remaps off-taxonomy keys,
-- retro-flags implausible/zero/duplicate rows, demotes duplicate verified
-- children, and gates the published_fee_catalog view on quality_flag = 'clean'.
--
-- Quarantine only: no row is deleted; every key remap is logged in
-- fee_key_remaps; flags are reversible by UPDATE.
--
-- Apply with psql against DATABASE_URL in a single transaction (see
-- docs/plans/production-migration-history-runbook-2026-08-15.md; db push
-- remains blocked by historical drift).

-- 1. Columns ----------------------------------------------------------------
ALTER TABLE published_fee_records
  ADD COLUMN IF NOT EXISTS quality_flag text NOT NULL DEFAULT 'clean',
  ADD COLUMN IF NOT EXISTS quality_reason text,
  ADD COLUMN IF NOT EXISTS observed_at timestamptz;

ALTER TABLE published_fee_records
  DROP CONSTRAINT IF EXISTS published_fee_records_quality_flag_check;
ALTER TABLE published_fee_records
  ADD CONSTRAINT published_fee_records_quality_flag_check
  CHECK (quality_flag IN ('clean', 'off_taxonomy', 'implausible', 'zero_amount', 'duplicate'));

CREATE INDEX IF NOT EXISTS published_fee_records_quality_idx
  ON published_fee_records (quality_flag)
  WHERE quality_flag <> 'clean';

-- Best available observation date for existing rows; the legacy-promotion
-- phase carries true archive observation dates.
UPDATE published_fee_records SET observed_at = published_at WHERE observed_at IS NULL;

-- 2. Reference tables -------------------------------------------------------
CREATE TABLE IF NOT EXISTS fee_taxonomy (
  canonical_key text PRIMARY KEY,
  fee_family text
);

CREATE TABLE IF NOT EXISTS fee_key_aliases (
  alias text PRIMARY KEY,
  canonical_key text NOT NULL REFERENCES fee_taxonomy (canonical_key)
);

CREATE TABLE IF NOT EXISTS fee_category_bands (
  canonical_key text PRIMARY KEY REFERENCES fee_taxonomy (canonical_key),
  min_amount numeric NOT NULL,
  max_amount numeric NOT NULL,
  frequencies text[],
  note text,
  source text NOT NULL
);

CREATE TABLE IF NOT EXISTS fee_key_remaps (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entity text NOT NULL,          -- 'published' | 'verified'
  entity_id bigint NOT NULL,
  old_key text NOT NULL,
  new_key text NOT NULL,
  remapped_at timestamptz NOT NULL DEFAULT now()
);

-- Generated by scripts/generate-fee-quality-seeds.mjs; do not hand-edit.
-- Sources: fee-taxonomy.ts (65 canonical keys, 197 aliases), fee-plausibility.ts (45 envelopes).
INSERT INTO fee_taxonomy (canonical_key, fee_family) VALUES
  ('account_research', 'Account Maintenance'),
  ('account_verification', 'Account Services'),
  ('ach_origination', 'Digital & Electronic'),
  ('ach_return', 'Digital & Electronic'),
  ('appraisal_fee', 'Lending Fees'),
  ('atm_international', 'ATM & Card'),
  ('atm_non_network', 'ATM & Card'),
  ('balance_inquiry', 'Account Services'),
  ('bill_pay', 'Digital & Electronic'),
  ('card_dispute', 'ATM & Card'),
  ('card_foreign_txn', 'ATM & Card'),
  ('card_replacement', 'ATM & Card'),
  ('cash_advance', 'Cash & Deposit'),
  ('cashiers_check', 'Check Services'),
  ('check_cashing', 'Check Services'),
  ('check_image', 'Check Services'),
  ('check_printing', 'Check Services'),
  ('coin_counting', 'Cash & Deposit'),
  ('continuous_od', 'Overdraft & NSF'),
  ('counter_check', 'Check Services'),
  ('courier_delivery', 'Other Fees'),
  ('deposited_item_return', 'Cash & Deposit'),
  ('dmv_filing', 'Vehicle & Title'),
  ('document_reproduction', 'Other Fees'),
  ('dormant_account', 'Account Maintenance'),
  ('duplicate_title', 'Vehicle & Title'),
  ('early_closure', 'Account Maintenance'),
  ('estatement_fee', 'Account Maintenance'),
  ('garnishment_levy', 'Account Services'),
  ('gift_card_purchase', 'Gift & Prepaid Cards'),
  ('ira_administration', 'Retirement & IRA'),
  ('ira_distribution', 'Retirement & IRA'),
  ('ira_termination', 'Retirement & IRA'),
  ('late_payment', 'Lending Fees'),
  ('legal_process', 'Account Services'),
  ('loan_origination', 'Lending Fees'),
  ('minimum_balance', 'Account Maintenance'),
  ('mobile_deposit', 'Digital & Electronic'),
  ('money_order', 'Check Services'),
  ('monthly_maintenance', 'Account Maintenance'),
  ('mortgage_lien_release', 'Mortgage Servicing'),
  ('mortgage_modification', 'Mortgage Servicing'),
  ('mortgage_payoff', 'Mortgage Servicing'),
  ('night_deposit', 'Cash & Deposit'),
  ('notary_fee', 'Account Services'),
  ('nsf', 'Overdraft & NSF'),
  ('nsf_daily_cap', 'Overdraft & NSF'),
  ('od_daily_cap', 'Overdraft & NSF'),
  ('od_line_of_credit', 'Overdraft & NSF'),
  ('od_protection_transfer', 'Overdraft & NSF'),
  ('other_lending_fee', 'Other Fees'),
  ('overdraft', 'Overdraft & NSF'),
  ('paper_statement', 'Account Maintenance'),
  ('prepaid_card_reload', 'Gift & Prepaid Cards'),
  ('reconveyance', 'Mortgage Servicing'),
  ('refinance_fee', 'Mortgage Servicing'),
  ('rush_card', 'ATM & Card'),
  ('safe_deposit_box', 'Account Services'),
  ('stop_payment', 'Check Services'),
  ('vehicle_title', 'Vehicle & Title'),
  ('wire_domestic_incoming', 'Wire Transfers'),
  ('wire_domestic_outgoing', 'Wire Transfers'),
  ('wire_intl_incoming', 'Wire Transfers'),
  ('wire_intl_outgoing', 'Wire Transfers'),
  ('zelle_fee', 'Digital & Electronic')
ON CONFLICT (canonical_key) DO UPDATE SET fee_family = EXCLUDED.fee_family;
INSERT INTO fee_key_aliases (alias, canonical_key) VALUES
  ('10_x_10', 'safe_deposit_box'),
  ('10_x_10_box', 'safe_deposit_box'),
  ('3_x_10', 'safe_deposit_box'),
  ('3_x_5', 'safe_deposit_box'),
  ('3_x_5_box', 'safe_deposit_box'),
  ('5_x_10', 'safe_deposit_box'),
  ('5_x_10_box', 'safe_deposit_box'),
  ('5_x_5', 'safe_deposit_box'),
  ('abandoned_property_fee', 'dormant_account'),
  ('account_balancing_assistance', 'account_research'),
  ('account_balancing_assistance_per_hour', 'account_research'),
  ('account_closed_within_90_days', 'early_closure'),
  ('account_closed_within_90_days_of_opening', 'early_closure'),
  ('account_research', 'account_research'),
  ('account_verification', 'account_verification'),
  ('ach_batch_fee', 'ach_origination'),
  ('ach_origination', 'ach_origination'),
  ('ach_return', 'ach_return'),
  ('all_other_atms', 'atm_non_network'),
  ('appraisal_fee', 'appraisal_fee'),
  ('atm_deposit_adjustment', 'deposited_item_return'),
  ('atm_international', 'atm_international'),
  ('atm_non_network', 'atm_non_network'),
  ('bad_address', 'account_research'),
  ('bad_address_fee', 'account_research'),
  ('balance_inquiry', 'balance_inquiry'),
  ('balancing_assistance_fee', 'account_research'),
  ('bill_pay', 'bill_pay'),
  ('box_drilling', 'safe_deposit_box'),
  ('card_dispute', 'card_dispute'),
  ('card_foreign_txn', 'card_foreign_txn'),
  ('card_replacement', 'card_replacement'),
  ('cash_advance', 'cash_advance'),
  ('cashed_fee', 'check_cashing'),
  ('cashiers_check', 'cashiers_check'),
  ('charitable_donation', 'account_research'),
  ('check_by_phone', 'check_cashing'),
  ('check_cashing', 'check_cashing'),
  ('check_fee', 'check_printing'),
  ('check_image', 'check_image'),
  ('check_image_charge', 'check_image'),
  ('check_printing', 'check_printing'),
  ('christmas_club_early_withdrawal', 'early_closure'),
  ('christmas_club_early_withdrawal_fee', 'early_closure'),
  ('christmas_club_withdrawal', 'early_closure'),
  ('christmas_club_withdrawal_fee', 'early_closure'),
  ('club_account', 'early_closure'),
  ('club_account_early_withdrawal', 'early_closure'),
  ('coin_counting', 'coin_counting'),
  ('coin_deposited_fee', 'coin_counting'),
  ('collection_fee', 'deposited_item_return'),
  ('continuous_od', 'continuous_od'),
  ('copy_of_paid_check', 'check_image'),
  ('corporate_check', 'cashiers_check'),
  ('counter_check', 'counter_check'),
  ('courier_delivery', 'courier_delivery'),
  ('credit_card_fee', 'cash_advance'),
  ('credit_fee', 'cash_advance'),
  ('debit_card_fee', 'card_replacement'),
  ('debit_card_rush_fee', 'rush_card'),
  ('debit_fee', 'card_replacement'),
  ('deposited_fee', 'deposited_item_return'),
  ('deposited_item_return', 'deposited_item_return'),
  ('dmv_filing', 'dmv_filing'),
  ('document_copy', 'account_research'),
  ('document_copy_fee', 'account_research'),
  ('document_reproduction', 'document_reproduction'),
  ('dormant_account', 'dormant_account'),
  ('dormant_fee', 'dormant_account'),
  ('drilling_fee', 'safe_deposit_box'),
  ('duplicate_lien_release', 'legal_process'),
  ('duplicate_title', 'duplicate_title'),
  ('early_closure', 'early_closure'),
  ('escheat_processing_fee', 'dormant_account'),
  ('escheatment', 'dormant_account'),
  ('estatement', 'estatement_fee'),
  ('estatement_fee', 'estatement_fee'),
  ('excessive_transaction_fee', 'account_research'),
  ('excessive_withdrawal_fee', 'overdraft'),
  ('express_mail', 'wire_domestic_outgoing'),
  ('fastpay_fee', 'ach_origination'),
  ('fax', 'account_research'),
  ('fax_fee', 'account_research'),
  ('fax_service', 'account_research'),
  ('fax_services', 'account_research'),
  ('foreign_check_collection', 'check_cashing'),
  ('garnishment_levy', 'garnishment_levy'),
  ('gift_card', 'gift_card_purchase'),
  ('gift_card_purchase', 'gift_card_purchase'),
  ('gift_cards', 'gift_card_purchase'),
  ('gift_pay', 'gift_card_purchase'),
  ('inactive_fee', 'dormant_account'),
  ('incorrect_address', 'account_research'),
  ('incorrect_address_fee', 'account_research'),
  ('inquiries_fee', 'account_research'),
  ('international_fee', 'card_foreign_txn'),
  ('invalid_address_fee', 'account_research'),
  ('ira_administration', 'ira_administration'),
  ('ira_distribution', 'ira_distribution'),
  ('ira_termination', 'ira_termination'),
  ('items_sent_for_collection', 'deposited_item_return'),
  ('key_replacement', 'safe_deposit_box'),
  ('late_payment', 'late_payment'),
  ('legal_process', 'legal_process'),
  ('less_fee', 'account_research'),
  ('lien_fee', 'legal_process'),
  ('loan_cancellation_fee', 'loan_origination'),
  ('loan_extension', 'loan_origination'),
  ('loan_modification_fee', 'loan_origination'),
  ('loan_origination', 'loan_origination'),
  ('lost_fee', 'safe_deposit_box'),
  ('lost_key', 'safe_deposit_box'),
  ('lost_key_fee', 'safe_deposit_box'),
  ('mailed_paper_statement', 'paper_statement'),
  ('membership_share', 'monthly_maintenance'),
  ('minimum_balance', 'minimum_balance'),
  ('mobile_deposit', 'mobile_deposit'),
  ('money_market_fee', 'monthly_maintenance'),
  ('money_order', 'money_order'),
  ('month_fee', 'monthly_maintenance'),
  ('monthly_maintenance', 'monthly_maintenance'),
  ('monthly_maintenance_charge', 'monthly_maintenance'),
  ('more_fee', 'account_research'),
  ('mortgage_lien_release', 'mortgage_lien_release'),
  ('mortgage_modification', 'mortgage_modification'),
  ('mortgage_payoff', 'mortgage_payoff'),
  ('mortgage_subordination', 'legal_process'),
  ('mortgage_subordination_fee', 'legal_process'),
  ('night_deposit', 'night_deposit'),
  ('nonsufficient_fee', 'nsf'),
  ('notary_fee', 'notary_fee'),
  ('nsf', 'nsf'),
  ('nsf_daily_cap', 'nsf_daily_cap'),
  ('od_daily_cap', 'od_daily_cap'),
  ('od_line_of_credit', 'od_line_of_credit'),
  ('od_protection_transfer', 'od_protection_transfer'),
  ('operate_fee', 'account_research'),
  ('other_lending_fee', 'other_lending_fee'),
  ('outgoing_domestic', 'wire_domestic_outgoing'),
  ('outgoing_fee', 'wire_domestic_outgoing'),
  ('over_fee', 'overdraft'),
  ('overdraft', 'overdraft'),
  ('overdraft_each_overdraft_paid', 'overdraft'),
  ('overdraft_privilege', 'overdraft'),
  ('paper_statement', 'paper_statement'),
  ('per_transaction_fee', 'account_research'),
  ('pin_fee', 'card_replacement'),
  ('pin_replacement', 'card_replacement'),
  ('pin_replacement_fee', 'card_replacement'),
  ('premier_fee', 'monthly_maintenance'),
  ('prepaid_card_reload', 'prepaid_card_reload'),
  ('reconveyance', 'reconveyance'),
  ('refinance_fee', 'refinance_fee'),
  ('reinstatement', 'late_payment'),
  ('reload_fee', 'prepaid_card_reload'),
  ('reopen_account', 'early_closure'),
  ('replacement_fee', 'card_replacement'),
  ('replacement_key', 'safe_deposit_box'),
  ('return_item_charge', 'nsf'),
  ('return_mail', 'account_research'),
  ('returned_mail', 'account_research'),
  ('returned_mail_fee', 'account_research'),
  ('returned_statement', 'paper_statement'),
  ('returned_wire', 'wire_domestic_outgoing'),
  ('rush_card', 'rush_card'),
  ('rush_card_delivery', 'rush_card'),
  ('safe_deposit', 'safe_deposit_box'),
  ('safe_deposit_box', 'safe_deposit_box'),
  ('savings_fee', 'monthly_maintenance'),
  ('shared_branch_fee', 'balance_inquiry'),
  ('silverbronze_rewards_fee', 'monthly_maintenance'),
  ('skip_a_pay', 'late_payment'),
  ('skipapay', 'late_payment'),
  ('skipapay_fee', 'late_payment'),
  ('skipapayment', 'late_payment'),
  ('skipapayment_fee', 'late_payment'),
  ('stop_payment', 'stop_payment'),
  ('subordination', 'legal_process'),
  ('subordination_fee', 'legal_process'),
  ('transaction_fee', 'account_research'),
  ('transactions_fee', 'account_research'),
  ('transfer_fee', 'od_protection_transfer'),
  ('undeliverable_mail', 'account_research'),
  ('vehicle_title', 'vehicle_title'),
  ('visa_debit_card_fee', 'card_replacement'),
  ('visa_gift_card', 'gift_card_purchase'),
  ('visa_gift_cards', 'gift_card_purchase'),
  ('visa_travel_card', 'card_replacement'),
  ('western_union', 'wire_domestic_outgoing'),
  ('wire_domestic_incoming', 'wire_domestic_incoming'),
  ('wire_domestic_outgoing', 'wire_domestic_outgoing'),
  ('wire_intl_incoming', 'wire_intl_incoming'),
  ('wire_intl_outgoing', 'wire_intl_outgoing'),
  ('withdrawal_fee', 'account_research'),
  ('zelle_fee', 'zelle_fee'),
  ('zipper_bag', 'night_deposit'),
  ('zipper_bags', 'night_deposit')
ON CONFLICT (alias) DO UPDATE SET canonical_key = EXCLUDED.canonical_key;
INSERT INTO fee_category_bands (canonical_key, min_amount, max_amount, frequencies, note, source) VALUES
  ('overdraft', 1, 60, ARRAY['per_item', 'per_transaction', 'one_time'], 'per-item overdraft charge', 'fee-plausibility v1'),
  ('nsf', 1, 60, ARRAY['per_item', 'per_transaction', 'one_time'], 'per-item NSF charge', 'fee-plausibility v1'),
  ('continuous_od', 1, 100, NULL, 'sustained-overdraft charge, often daily', 'fee-plausibility v1'),
  ('od_protection_transfer', 0, 30, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('od_line_of_credit', 0, 50, NULL, NULL, 'fee-plausibility v1'),
  ('od_daily_cap', 10, 750, ARRAY['daily'], 'daily overdraft ceiling', 'fee-plausibility v1'),
  ('nsf_daily_cap', 10, 750, ARRAY['daily'], 'daily NSF ceiling', 'fee-plausibility v1'),
  ('monthly_maintenance', 1, 75, ARRAY['monthly'], 'monthly consumer checking charge', 'fee-plausibility v1'),
  ('minimum_balance', 1, 75, ARRAY['monthly'], NULL, 'fee-plausibility v1'),
  ('paper_statement', 0.2, 15, ARRAY['monthly'], NULL, 'fee-plausibility v1'),
  ('estatement_fee', 0.5, 15, ARRAY['monthly'], NULL, 'fee-plausibility v1'),
  ('early_closure', 5, 100, NULL, NULL, 'fee-plausibility v1'),
  ('dormant_account', 1, 50, NULL, NULL, 'fee-plausibility v1'),
  ('account_research', 0.25, 100, NULL, 'printout through hourly research', 'fee-plausibility v1'),
  ('atm_non_network', 0.5, 10, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('atm_international', 0.5, 15, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('card_replacement', 1, 50, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('rush_card', 5, 150, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('card_foreign_txn', 0.5, 15, NULL, 'flat charge; percentage rates are not amounts', 'fee-plausibility v1'),
  ('card_dispute', 0, 50, NULL, NULL, 'fee-plausibility v1'),
  ('wire_domestic_outgoing', 5, 75, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('wire_domestic_incoming', 0, 50, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('wire_intl_outgoing', 10, 125, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('wire_intl_incoming', 0, 75, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('cashiers_check', 1, 40, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('money_order', 0.5, 20, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('stop_payment', 5, 60, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('counter_check', 0.25, 20, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('check_printing', 5, 60, NULL, NULL, 'fee-plausibility v1'),
  ('check_image', 0.25, 20, ARRAY['monthly'], NULL, 'fee-plausibility v1'),
  ('check_cashing', 1, 30, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('deposited_item_return', 1, 50, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('coin_counting', 0.5, 25, NULL, NULL, 'fee-plausibility v1'),
  ('cash_advance', 1, 50, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('ach_return', 1, 50, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('ach_origination', 0.1, 50, NULL, NULL, 'fee-plausibility v1'),
  ('bill_pay', 0.5, 20, ARRAY['monthly', 'per_item'], NULL, 'fee-plausibility v1'),
  ('mobile_deposit', 0.1, 15, ARRAY['monthly'], NULL, 'fee-plausibility v1'),
  ('notary_fee', 1, 30, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('safe_deposit_box', 1, 400, NULL, NULL, 'fee-plausibility v1'),
  ('garnishment_levy', 10, 150, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('legal_process', 10, 200, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('account_verification', 1, 50, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('balance_inquiry', 0.25, 10, ARRAY['per_item', 'per_transaction', 'one_time'], NULL, 'fee-plausibility v1'),
  ('night_deposit', 1, 100, NULL, NULL, 'fee-plausibility v1')
ON CONFLICT (canonical_key) DO UPDATE SET min_amount = EXCLUDED.min_amount, max_amount = EXCLUDED.max_amount, frequencies = EXCLUDED.frequencies, note = EXCLUDED.note, source = EXCLUDED.source;

-- 3. Remap off-taxonomy canonical keys (logged) -----------------------------
WITH remapped AS (
  UPDATE published_fee_records p
     SET canonical_fee_key = a.canonical_key
    FROM fee_key_aliases a
   WHERE a.alias = p.canonical_fee_key
     AND a.canonical_key <> p.canonical_fee_key
  RETURNING p.fee_published_id, a.alias AS old_key, a.canonical_key AS new_key
)
INSERT INTO fee_key_remaps (entity, entity_id, old_key, new_key)
SELECT 'published', fee_published_id, old_key, new_key FROM remapped;

WITH remapped AS (
  UPDATE verified_fee_observations v
     SET canonical_fee_key = a.canonical_key
    FROM fee_key_aliases a
   WHERE a.alias = v.canonical_fee_key
     AND a.canonical_key <> v.canonical_fee_key
  RETURNING v.fee_verified_id, a.alias AS old_key, a.canonical_key AS new_key
)
INSERT INTO fee_key_remaps (entity, entity_id, old_key, new_key)
SELECT 'verified', fee_verified_id, old_key, new_key FROM remapped;

-- Anything still off-taxonomy (unmappable) is quarantined, not deleted.
UPDATE published_fee_records p
   SET quality_flag = 'off_taxonomy',
       quality_reason = 'canonical_fee_key not in fee_taxonomy and no alias maps it'
 WHERE quality_flag = 'clean'
   AND NOT EXISTS (SELECT 1 FROM fee_taxonomy t WHERE t.canonical_key = p.canonical_fee_key);

-- 4. Hygiene ----------------------------------------------------------------
UPDATE published_fee_records p
   SET source_url = s.fee_schedule_url
  FROM institution_sources s
 WHERE s.id = p.institution_id
   AND p.source_url IS NULL
   AND s.fee_schedule_url IS NOT NULL;

UPDATE fee_change_records SET change_type = 'increased' WHERE change_type = 'increase';

-- 5. Retro-flag amounts -----------------------------------------------------
UPDATE published_fee_records
   SET quality_flag = 'implausible', quality_reason = 'amount is NULL'
 WHERE quality_flag = 'clean' AND amount IS NULL;

UPDATE published_fee_records
   SET quality_flag = 'zero_amount', quality_reason = 'amount is $0 (no-charge line)'
 WHERE quality_flag = 'clean' AND amount = 0;

UPDATE published_fee_records p
   SET quality_flag = 'implausible',
       quality_reason = format('amount %s outside band [%s, %s] (%s)',
                               p.amount, b.min_amount, b.max_amount, b.source)
  FROM fee_category_bands b
 WHERE b.canonical_key = p.canonical_fee_key
   AND p.quality_flag = 'clean'
   AND (p.amount < b.min_amount OR p.amount > b.max_amount);

-- Default ceiling for keys without a band (mirrors DEFAULT_MAX_AMOUNT).
UPDATE published_fee_records p
   SET quality_flag = 'implausible',
       quality_reason = format('amount %s above default ceiling 2500 (no band for %s)',
                               p.amount, p.canonical_fee_key)
 WHERE p.quality_flag = 'clean'
   AND p.amount > 2500
   AND NOT EXISTS (SELECT 1 FROM fee_category_bands b WHERE b.canonical_key = p.canonical_fee_key);

-- 6. Duplicate flagging (keep the lowest id per identical clean line) -------
WITH ranked AS (
  SELECT fee_published_id,
         row_number() OVER (
           PARTITION BY institution_id, canonical_fee_key, COALESCE(variant_type, ''), amount
           ORDER BY fee_published_id
         ) AS rn
    FROM published_fee_records
   WHERE quality_flag = 'clean' AND rolled_back_at IS NULL
)
UPDATE published_fee_records p
   SET quality_flag = 'duplicate',
       quality_reason = 'identical (institution, key, variant, amount) line kept under a lower id'
  FROM ranked r
 WHERE r.fee_published_id = p.fee_published_id AND r.rn > 1;

-- 7. Demote duplicate verified children -------------------------------------
-- The review_status check predates the quarantine flow; extend it first.
ALTER TABLE verified_fee_observations
  DROP CONSTRAINT verified_fee_observations_review_status_check;
ALTER TABLE verified_fee_observations
  ADD CONSTRAINT verified_fee_observations_review_status_check
  CHECK ((review_status = ANY (ARRAY['superseded_duplicate'::text, 'verified'::text, 'challenged'::text, 'rejected'::text, 'approved'::text])));

-- A raw observation is one fee line; keep one verified child per raw
-- (preferring the one a clean published row points at), demote the rest so
-- the publish path stops seeing them. Demotion is reversible.
WITH dup_raws AS (
  SELECT fee_raw_id FROM verified_fee_observations GROUP BY 1 HAVING count(*) > 1
), ranked AS (
  SELECT v.fee_verified_id,
         row_number() OVER (
           PARTITION BY v.fee_raw_id
           ORDER BY (EXISTS (
                      SELECT 1 FROM published_fee_records p
                       WHERE p.lineage_ref = v.fee_verified_id
                         AND p.rolled_back_at IS NULL
                         AND p.quality_flag = 'clean')) DESC,
                    v.fee_verified_id
         ) AS rn
    FROM verified_fee_observations v
    JOIN dup_raws d ON d.fee_raw_id = v.fee_raw_id
)
UPDATE verified_fee_observations v
   SET review_status = 'superseded_duplicate'
  FROM ranked r
 WHERE r.fee_verified_id = v.fee_verified_id AND r.rn > 1
   AND v.review_status IN ('verified', 'approved');

CREATE UNIQUE INDEX IF NOT EXISTS verified_fee_observations_one_live_per_raw
  ON verified_fee_observations (fee_raw_id)
  WHERE review_status IN ('verified', 'approved');

-- 8. Gate the catalog view --------------------------------------------------
CREATE OR REPLACE VIEW published_fee_catalog AS
 SELECT fp.fee_published_id AS id,
    fp.fee_published_id,
    fp.lineage_ref AS fee_verified_id,
    fv.fee_raw_id,
    fp.institution_id,
    fp.fee_name,
    fp.amount,
    fp.frequency,
    fr.conditions,
    COALESCE(fp.extraction_confidence, fv.extraction_confidence, fr.extraction_confidence) AS extraction_confidence,
    'approved'::text AS review_status,
    COALESCE(fv.outlier_flags, '[]'::jsonb) AS validation_flags,
    fp.canonical_fee_key AS fee_category,
    fp.canonical_fee_key,
    NULL::text AS fee_family,
    NULL::text AS account_product_type,
    false AS is_fee_cap,
    fp.variant_type,
    fp.coverage_tier,
    COALESCE(fp.source_url, fv.source_url, fr.source_url) AS source_url,
    fr.source,
    COALESCE(fp.source_url, fv.source_url, fr.source_url) AS document_url,
    COALESCE(fp.document_r2_key, fv.document_r2_key, fr.document_r2_key) AS document_r2_key,
    fr.source_document_id,
    COALESCE(fp.agent_event_id, fr.agent_event_id) AS agent_event_id,
    COALESCE(fp.verified_by_agent_event_id, fv.verified_by_agent_event_id) AS verified_by_agent_event_id,
    fp.published_by_adversarial_event_id,
    fp.batch_id,
    fp.published_at AS created_at,
    fp.published_at AS updated_at,
    fp.quality_flag,
    fp.observed_at
   FROM published_fee_records fp
     LEFT JOIN verified_fee_observations fv ON fv.fee_verified_id = fp.lineage_ref
     LEFT JOIN raw_fee_observations fr ON fr.fee_raw_id = fv.fee_raw_id
  WHERE fp.rolled_back_at IS NULL
    AND fp.quality_flag = 'clean';

-- 9. Invariants (abort the transaction if the gate failed) ------------------
DO $$
DECLARE n bigint;
BEGIN
  SELECT count(*) INTO n FROM published_fee_records p
   WHERE p.quality_flag = 'clean'
     AND NOT EXISTS (SELECT 1 FROM fee_taxonomy t WHERE t.canonical_key = p.canonical_fee_key);
  IF n > 0 THEN RAISE EXCEPTION 'quality gate: % clean rows off-taxonomy', n; END IF;

  SELECT count(*) INTO n FROM (
    SELECT 1 FROM published_fee_records
     WHERE quality_flag = 'clean' AND rolled_back_at IS NULL
     GROUP BY institution_id, canonical_fee_key, COALESCE(variant_type, ''), amount
    HAVING count(*) > 1) d;
  IF n > 0 THEN RAISE EXCEPTION 'quality gate: % duplicate clean groups remain', n; END IF;

  SELECT count(*) INTO n FROM published_fee_records
   WHERE quality_flag = 'clean' AND (amount IS NULL OR amount = 0);
  IF n > 0 THEN RAISE EXCEPTION 'quality gate: % clean rows with NULL/zero amount', n; END IF;
END $$;

INSERT INTO supabase_migrations.schema_migrations (version, name, statements)
VALUES ('20270101070000', 'published_fee_quality_gate', ARRAY['-- applied manually via psql per migration runbook'])
ON CONFLICT (version) DO NOTHING;
