// AUTO-GENERATED by scripts/gen-agent-tool-types.sh — DO NOT EDIT BY HAND.
// Source of truth: fee_crawler/agent_tools/schemas/ (package)
// Regenerate: bash scripts/gen-agent-tool-types.sh

// NOTE: This file was generated with pydantic-to-typescript v2. If you edit
// schemas/_base.py or any per-domain schema module (fees.py, crawl.py, etc.),
// rerun the codegen script before committing.
//
// Plan 62A-05 ships only the shared base types below. Per-domain interfaces
// (ApproveFeeRawInput, CreateHamiltonScenarioInput, ...) land here after
// Plans 62A-07..10 add their per-domain Pydantic modules AND the codegen
// script is rerun.

export interface BaseToolInput {}

export interface BaseToolOutput {
  success: boolean;
  error?: string | null;
}

export interface AgentEventRef {
  event_id: string;
  correlation_id: string;
}

export type AgentName = "hamilton" | "knox" | "darwin" | "atlas";
