/**
 * AnalysisPdfDocument — @react-pdf/renderer document component for Analyze screen exports.
 * Server-side ONLY. Never import this in client components.
 * Called from /api/pro/report-pdf route only (via type: "analysis" dispatch).
 *
 * Design: Mirrors PdfDocument.tsx brand palette — same COLORS, same StyleSheet patterns.
 * No CSS variables (react-pdf cannot resolve them).
 */
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import type { AnalyzeResponse } from "@/lib/hamilton/types";

// ─── Brand Colors ─────────────────────────────────────────────────────────────
// Exact copy from PdfDocument.tsx — do not use CSS variables here.

const COLORS = {
  textPrimary: "#1c1917",
  textSecondary: "#78716c",
  textTertiary: "#a8a29e",
  accent: "#b45309",
  surface: "#fbf9f4",
  surfaceElevated: "#f5f1e8",
  borderDark: "#d6d0c5",
};

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  page: {
    backgroundColor: COLORS.surface,
    paddingTop: 64,
    paddingBottom: 64,
    paddingLeft: 72,
    paddingRight: 72,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 32,
    paddingBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderDark,
    borderBottomStyle: "solid",
  },
  reportTypeBadge: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: COLORS.accent,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 12,
  },
  reportTitle: {
    fontSize: 24,
    fontFamily: "Helvetica-Bold",
    color: COLORS.textPrimary,
    lineHeight: 1.2,
    marginBottom: 8,
  },
  readOnlyNotice: {
    fontSize: 8,
    color: COLORS.textTertiary,
    fontFamily: "Helvetica",
  },
  section: {
    marginBottom: 32,
    paddingBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderDark,
    borderBottomStyle: "solid",
  },
  sectionHeading: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: COLORS.textPrimary,
    marginBottom: 12,
    lineHeight: 1.3,
  },
  paragraph: {
    fontSize: 11,
    fontFamily: "Helvetica",
    color: COLORS.textPrimary,
    lineHeight: 1.7,
    marginBottom: 10,
  },
  statCalloutGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 8,
  },
  statCalloutBox: {
    backgroundColor: COLORS.surfaceElevated,
    padding: 12,
    borderRadius: 4,
    width: "46%",
  },
  statCalloutLabel: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: COLORS.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
  },
  statCalloutRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  statValue: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    color: COLORS.textPrimary,
  },
  statValueAccent: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    color: COLORS.accent,
  },
  statNote: {
    fontSize: 8,
    fontFamily: "Helvetica",
    color: COLORS.textTertiary,
    marginTop: 4,
  },
  noteItem: {
    fontSize: 10,
    fontFamily: "Helvetica",
    color: COLORS.textSecondary,
    lineHeight: 1.6,
    marginBottom: 6,
    paddingLeft: 12,
  },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 72,
    right: 72,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderDark,
    borderTopStyle: "solid",
    paddingTop: 12,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerText: {
    fontSize: 8,
    fontFamily: "Helvetica",
    color: COLORS.textTertiary,
  },
});

// ─── Component ────────────────────────────────────────────────────────────────

interface AnalysisPdfDocumentProps {
  analysis: AnalyzeResponse;
  analysisFocus: string;
  institutionName?: string;
}

export function AnalysisPdfDocument({
  analysis,
  analysisFocus,
  institutionName,
}: AnalysisPdfDocumentProps) {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Split hamiltonView on double newlines for multiple paragraphs
  const hamiltonViewParagraphs = analysis.hamiltonView
    .split(/\n\n+/)
    .map((p) => p.trim())
    .filter(Boolean);

  const readOnlyLine = institutionName
    ? `Generated by Hamilton — Bank Fee Index | ${institutionName}`
    : "Generated by Hamilton — Bank Fee Index";

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.reportTypeBadge}>{analysisFocus} Analysis</Text>
          <Text style={styles.reportTitle}>{analysis.title}</Text>
          <Text style={styles.readOnlyNotice}>{readOnlyLine}</Text>
        </View>

        {/* Hamilton's View */}
        <View style={styles.section}>
          <Text style={styles.sectionHeading}>{"Hamilton's View"}</Text>
          {hamiltonViewParagraphs.map((para, i) => (
            <Text key={i} style={styles.paragraph}>
              {para}
            </Text>
          ))}
        </View>

        {/* What This Means */}
        {analysis.whatThisMeans ? (
          <View style={styles.section}>
            <Text style={styles.sectionHeading}>What This Means</Text>
            <Text style={styles.paragraph}>{analysis.whatThisMeans}</Text>
          </View>
        ) : null}

        {/* Why It Matters */}
        {analysis.whyItMatters.length > 0 ? (
          <View style={styles.section}>
            <Text style={styles.sectionHeading}>Why It Matters</Text>
            {analysis.whyItMatters.map((item, i) => (
              <Text key={i} style={styles.noteItem}>
                {"-- "}{item}
              </Text>
            ))}
          </View>
        ) : null}

        {/* Evidence */}
        {analysis.evidence.metrics.length > 0 ? (
          <View style={styles.section}>
            <Text style={styles.sectionHeading}>Evidence</Text>
            <View style={styles.statCalloutGrid}>
              {analysis.evidence.metrics.map((metric, i) => (
                <View key={i} style={styles.statCalloutBox}>
                  <Text style={styles.statCalloutLabel}>{metric.label}</Text>
                  <View style={styles.statCalloutRow}>
                    <Text style={styles.statValue}>{metric.value}</Text>
                  </View>
                  {metric.note ? (
                    <Text style={styles.statNote}>{metric.note}</Text>
                  ) : null}
                </View>
              ))}
            </View>
          </View>
        ) : null}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Hamilton — Bank Fee Index</Text>
          <Text style={styles.footerText}>{today}</Text>
        </View>
      </Page>
    </Document>
  );
}
